# Circle CI Documentation https://circleci.com/docs/2.0/

version: 2.0

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: microsoft/dotnet:2.0.0-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - checkout
      - run: ./build.sh --target Test